import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import React from "react";
import { SessionProvider } from "next-auth/react";
import { ModalProvider } from "@/components/providers/modal-provider";
import { Toaster } from "@/components/ui/toaster";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`${recursive.className}  `}>
          <ReactQueryProvider>
            <ModalProvider />
            <Toaster />
            {children}
          </ReactQueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
